### ISSUE TITLE
Don't work anymore?

### ISSUE THREAD

**Issue by sdysj** [cnbeining/BiliLeupload#2]
乐视云更新了机制了吗？现在无法上传了。

懒癌羞涩求更新。

**Comment by cnbeining** [comment]
我找时间看看。

最近乐视接口抽风，也请等几个小时多试试。薯片很喜欢半夜玩维护和/或部署。

B

sdysj notifications@github.com于2015年8月5日星期三写道：

**Comment by cnbeining** [comment]
复测正常。

怀疑是乐视云晚间升级。

如果问题继续，请重开issue。

B

**Comment by sdysj** [comment]
不行啊?

```
Uploading 1 in 1 files...
ERROR: BiliLeUpload failed: u'Cannot get response from server!'
       If you think this should not happen, please open a issue at https://github.com/cnbeining/acupload/issues .
       Make sure you delete all the sensive data before you post it publicly.
Traceback (most recent call last):
  File "./bilileupload.py", line 257, in <module>
    upload(file2Upload, proxytype= proxytype, proxy_address= proxy_address, curl_args = curl_args, cookies = cookies)
  File "./bilileupload.py", line 110, in upload
    raise LetvUploadAPICannotReachException(u'Cannot get response from server!')
LetvUploadAPICannotReachException: u'Cannot get response from server!'
```
